spring:
  profiles:
    active: default, with-mtx
  datasource:
    embedded-database-connection: none
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
cds:
  multi-tenancy:
    mtxs:
      enabled: true
    sidecar:
      url: http://localhost:4005/
  security:
    mock:
      users:
        bob:
          roles:
            - cds.ExtensionDeveloper
          tenant: t1
        alice:
          roles:
            - admin
          tenant: t1
        erin:
          roles:
            - cds.ExtensionDeveloper
            - admin
          tenant: t2

management:
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      ping:
        enabled: true
      db:
        enabled: true
      enabled: true

