spring:
#  cds:
#    data-source.auto-config.enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  profiles:
    active: postgres-docker, with-mtx

---
spring:
  config.activate.on-profile: with-mtx
cds:
  multi-tenancy:
    sidecar.url: http://localhost:4005/ # in production mode overwrite with the URL from mta.yaml
    mtxs.enabled: true
  security.mock.users:
    alice:
      tenant: t1
      roles: [ admin ]
    bob:
      tenant: t1
      roles: [ cds.ExtensionDeveloper ]
    erin:
      tenant: t2
      roles: [ admin, cds.ExtensionDeveloper ]
