spring:
#  config.activate.on-profile: postgres-docker
#  cds:
#    data-source.auto-config.enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

---
spring:
  config.activate.on-profile: with-mtx
cds:
  multi-tenancy:
    sidecar.url: http://localhost:4005/ # in production mode overwrite with the URL from mta.yaml
