spring:
#  config.activate.on-profile: postgres-docker
#  cds:
#    data-source.auto-config.enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

